#include<stdio.h>
 
 int main()
{
	
	float a,b,c,area;
    
 	printf("the number A=");
	scanf("%f",&a);
	printf("the number B=");
	scanf("%f",&a);
	area=a*a;
  	printf("area of square a*a=%.2f",area);
   	
	printf("\nthe number A=");
  	scanf("%f",&a);
   	printf("the number B=");
	scanf("%f",&b);
	area=a*b;
   	printf("area of rectangle a*b=%.2f",area);
	
	printf("\nthe number A=");
	scanf("%f",&a);
	printf("the number B=");
	scanf("%f",&b);
	area=a/2*b*b;
	printf("area of triangle a/2*b*b=%f",area);   

	
	    

	
	
    
 
  	
}





